Feat/record
ljpalaciom/proyectoSoftware pull request #8
Opened 2020-03-09 23:40 UTC by sgiraldog

2020-03-09 23:45 UTC, ljpalaciom requested changes

2020-03-09 23:45 UTC, ljpalaciom commented on app/Http/Controllers/RecordController.php
> +        $chart->dataset('Weight by month', 'line', $record->pluck('weight')->all())->color("rgb(0, 102, 255)");
Lang please

2020-03-09 23:55 UTC, ljpalaciom requested changes

2020-03-09 23:55 UTC, ljpalaciom commented on app/Http/Controllers/RecordController.php
> +      $data["title"] = "Records";
Use lang please

2020-03-09 23:55 UTC, ljpalaciom commented on app/Http/Controllers/RecordController.php
> +
Please don't add two spaces.

2020-03-09 23:55 UTC, ljpalaciom commented on app/Http/Controllers/RecordController.php
> +      $data["title"] = "Records";
Lang please

2020-03-09 23:55 UTC, ljpalaciom commented on app/Http/Controllers/RecordController.php
> +      $data["title"] = "Record";
Lang please

2020-03-09 23:55 UTC, ljpalaciom commented on app/Record.php
> +
Please don't add two spaces.

2020-03-09 23:55 UTC, ljpalaciom commented on routes/web.php
> +Route::get('/record/delete/{id}', 'RecordController@delete')->name("record.delete"); //TODO: Change to Delete (Crashes).
Put post, to solve the problem you have to change the form with the method delete

2020-03-10 00:01 UTC, sgiraldog commented
Done

2020-03-10 00:02 UTC, ljpalaciom approved these changes

2020-03-10 00:02 UTC, merged